# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robot_control/contact.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class contact(genpy.Message):
  _md5sum = "05a794a2e3c1dcb7a9232a6e3a8e219d"
  _type = "robot_control/contact"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int64 contact1
int64 contact2
int64 contact3
int64 contact4
int64 contact5
"""
  __slots__ = ['contact1','contact2','contact3','contact4','contact5']
  _slot_types = ['int64','int64','int64','int64','int64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       contact1,contact2,contact3,contact4,contact5

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(contact, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.contact1 is None:
        self.contact1 = 0
      if self.contact2 is None:
        self.contact2 = 0
      if self.contact3 is None:
        self.contact3 = 0
      if self.contact4 is None:
        self.contact4 = 0
      if self.contact5 is None:
        self.contact5 = 0
    else:
      self.contact1 = 0
      self.contact2 = 0
      self.contact3 = 0
      self.contact4 = 0
      self.contact5 = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_5q().pack(_x.contact1, _x.contact2, _x.contact3, _x.contact4, _x.contact5))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.contact1, _x.contact2, _x.contact3, _x.contact4, _x.contact5,) = _get_struct_5q().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_5q().pack(_x.contact1, _x.contact2, _x.contact3, _x.contact4, _x.contact5))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.contact1, _x.contact2, _x.contact3, _x.contact4, _x.contact5,) = _get_struct_5q().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5q = None
def _get_struct_5q():
    global _struct_5q
    if _struct_5q is None:
        _struct_5q = struct.Struct("<5q")
    return _struct_5q
